// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

package server

import (
	"context"

	"space/user/internal/logic"
	"space/user/internal/svc"
	"space/user/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user.UserReq) (*user.UserRsp, error) {
	l := logic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) GetUser(ctx context.Context, in *user.GetUserReq) (*user.GetUserRsp, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}
