// Code generated by goctl. DO NOT EDIT!
// Source: user.proto

//go:generate mockgen -destination ./user_mock.go -package userclient -source $GOFILE

package userclient

import (
	"context"

	"space/user/user"

	"github.com/tal-tech/go-zero/zrpc"
)

type (
	UserReq    = user.UserReq
	UserRsp    = user.UserRsp
	GetUserReq = user.GetUserReq
	GetUserRsp = user.GetUserRsp

	User interface {
		Login(ctx context.Context, in *UserReq) (*UserRsp, error)
		GetUser(ctx context.Context, in *GetUserReq) (*GetUserRsp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) Login(ctx context.Context, in *UserReq) (*UserRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.Login(ctx, in)
}

func (m *defaultUser) GetUser(ctx context.Context, in *GetUserReq) (*GetUserRsp, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in)
}
